name: API Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-tests:
    name: Bruno API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli

      - name: Run Auth API Tests
        run: npx @usebruno/cli run bruno-collections/auth-api -r --env Development --reporter-html auth-results.html

      - name: Run Users API Tests
        run: npx @usebruno/cli run bruno-collections/users-api -r --env Development --reporter-html users-results.html

      - name: Run Products API Tests
        run: npx @usebruno/cli run bruno-collections/products-api -r --env Development --reporter-html products-results.html

      - name: Generate Combined Report
        run: npx @usebruno/cli run bruno-collections/auth-api -r --env Development --reporter-json results.json

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: api-test-results
          path: |
            *-results.html

  data-driven-tests:
    name: Data-Driven Tests (Optional)
    runs-on: ubuntu-latest
    needs: api-tests
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli

      - name: Verify data files exist
        run: |
          ls -la data/
          cat data/users.csv
          cat data/products.json

      - name: Run CSV Data Tests
        run: npm run test:data-csv || echo "CSV tests failed, continuing..."

      - name: Run JSON Data Tests
        run: npm run test:data-json || echo "JSON tests failed, continuing..."

      - name: Run Scenario Tests
        run: npm run test:scenarios || echo "Scenario tests failed, continuing..."
